apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web-app
          image: aphraz/node-app:1.1.1-staging
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "300m"
              memory: "512Mi"
            requests:
              cpu: "150m"
              memory: "256Mi"
      restartPolicy: Always
      strategy:
      type: RollingUpdate
      rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1